### ISSUE TITLE
Add support for managing stacks cross-region

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-cloudformation-controller-for-flux#8]
The CFN controller currently supports deploying stacks to only a single region, specified by the `AWS_REGION` environment variable in the controller's environment.   I'm not sure whether we should follow the ACK example of binding regions to namespaces (so all stacks in a namespace will be deployed to the same region) or if each CloudFormationStack object should be annotated with the region it belongs in.

https://aws-controllers-k8s.github.io/community/docs/user-docs/multi-region-resource-management/

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: production
  annotations:
    cloudformation.contrib.fluxcd.io/default-region: us-east-1
```

Related to this issue will be managing multiple S3 template buckets in the CFN controller.  Today, the CFN controller supports only a single template bucket for all CloudFormationStack objects, specified by the TEMPLATE_BUCKET environment variable.  Once we have multi-region support, each region managed by the CFN controller will need its own template bucket within that region.
